### ISSUE TITLE
Checklist A10

### ISSUE THREAD

**Issue by msramalho** [msramalho/feup-lbaw#37]
### [doku checklist](https://web.fe.up.pt/~jlopes/doku.php/teach/lbaw/stuff/checklist)
- [x] Implement privileged authentication (sign-up, sign-in, password recovery).
- [x] Implement support for mobile devices (responsiveness).
- [x] Implement search using the full-text search features of PostgreSQL.
- [x] Implementing online help.
- [x] Ensure isolation of various system layers following Laravel's architecture.
- [x] Implement an architecture to handle internal errors.
- [x] Implement AJAX calls.
- [x] Validate data entered by the user in forms using HTML5.
- [x] Validate data entered by the user in forms using JavaScript.
- [x] Validate data entered by the user in forms using Laravel.
- [x] Check HTML and CSS code using the W3C validation tools.
- [x] Check the accessibility of interfaces using automated tools and checklists.
- [x] Check the usability of the product based on checklists of common web usability problems.
- [x] Remove test and development comments from source code.
- [x] Remove temporary or unused files from the delivered source code.
- [x] Create a new release (A10) on the GitHub repository
- [x] Include a list of features in the product artifact (A10), indicating the implementation status of each feature (as a percentage).
- [x] Ensure the product is available, inside the FEUP VPN, at http://lbaw17GG.lbaw-prod.fe.up.pt.
- [x] Include the URL of the product in A10.
- [x] Include product access credentials (with different levels of permissions) in A10.
- [x] Remove test data from the database.
- [x] Populate the database with good (realistic) examples.
- [x] ~Prepare and publish the script for product demonstration.~
